### ISSUE TITLE
stream timeout

### ISSUE THREAD

**Issue by usama-asfar** [adrey/slack-file-upload-action#18]
I had been using `slack-file-upload-action` using for a while to upload APK to the Slack channel it was working fine but last two days getting `stream timeout` error but APK is getting uploaded successfully on the Slack channel. 

**Workflow** 
```
      - name: Upload APK to slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          channel: qa-testing
          title: Stage APK
```

`slack-file-upload-action` log
```
##[group***Run adrey/slack-file-upload-action@master
with:
  token: ***
  path: android/app/build/outputs/apk/release/app-release-unsigned-signed.apk
  channel: qa-testing
  title: Stage APK
env:
  SIGNED_RELEASE_FILE: android/app/build/outputs/apk/release/app-release-unsigned-signed.apk
##[endgroup***
undefined:1
stream timeout
^

SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/adrey/slack-file-upload-action/master/dist/index.js:77:37)
    at IncomingMessage.emit (events.js:[2](https://github.com/tripsido/app/runs/5037381428?check_suite_focus=true#step:15:2)15:7)
    at endReadableNT (_stream_readable.js:118[4](https://github.com/tripsido/app/runs/5037381428?check_suite_focus=true#step:15:4):12)
    at processTicksAndRejections (internal/process/task_queues.js:[8](https://github.com/tripsido/app/runs/5037381428?check_suite_focus=true#step:15:8)0:21)
```
